"""Write the Windows version resource from the helper's own __version__.

One number, in desktop/helper.py, so the executable's Properties, the MSI and
the log can never disagree about which build this is.
"""
import pathlib
import re

here = pathlib.Path(__file__).resolve().parent
version = re.search(r'__version__ = "([0-9.]+)"',
                    (here.parent / "helper.py").read_text(encoding="utf-8")).group(1)
parts = tuple(int(x) for x in version.split(".")) + (0,) * (4 - len(version.split(".")))

(here / "version_info.txt").write_text(f'''# Generated by write_version_info.py. Do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={parts},
    prodvers={parts},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        "040904B0",
        [StringStruct("CompanyName", "hSenid Mobile Solutions"),
         StringStruct("FileDescription", "SafePII desktop helper"),
         StringStruct("FileVersion", "{version}"),
         StringStruct("InternalName", "SafePIIHelper"),
         StringStruct("LegalCopyright", "Copyright (c) hSenid Mobile Solutions"),
         StringStruct("OriginalFilename", "SafePIIHelper.exe"),
         StringStruct("ProductName", "SafePII"),
         StringStruct("ProductVersion", "{version}")])
    ]),
    VarFileInfo([VarStruct("Translation", [1033, 1200])])
  ]
)
''', encoding="utf-8")
print("version_info.txt written for", version)
