#!/usr/bin/env bash
# Install or update Maskroom on the server from a shipped image. Runs in the deploy
# directory (default /hms/apps/masking), which holds only:
#   docker-compose.server.yml  install.sh  nginx/maskroom.conf.template  keycloak/realm-maskroom.json
#   .env (created here)  certs/ (created here)  data/ (runtime)
# deploy/aws/ship.sh builds the image on a workstation, loads it here and runs this.
#   MASKROOM_IMAGE=maskroom:<tag> ./install.sh
# Idempotent: .env, certificates and data are kept. MASKROOM_INSTALL_DRY_RUN=1 renders
# the files and stops before anything is started.
set -euo pipefail
cd "$(dirname "$0")"
DEPLOY=$(pwd)
CERT_DIR=${CERT_DIR:-$DEPLOY/certs}
PLATFORM_DIR=${PLATFORM_DIR:-/hms/apps/sovereign-ai}
COMPOSE="docker compose -f docker-compose.server.yml --profile keycloak"

say()  { printf '\n==> %s\n' "$*"; }
rand() { openssl rand -hex "${1:-32}"; }
need() { command -v "$1" >/dev/null || { echo "missing: $1"; exit 1; }; }
need docker; need openssl; need sed

# ------------------------------------------------------------------ .env
if [ ! -f .env ]; then
  say "Creating .env with generated secrets"
  read -rp "Maskroom domain (e.g. safepii.hsenidmobile.com): " DOMAIN
  read -rp "Admin emails, comma-separated (become admin on first sign-in): " ADMINS
  cat > .env <<ENV
# Maskroom server configuration. Secrets generated by install.sh on $(date -I).
COMPOSE_PROJECT_NAME=maskroom
MASKROOM_IMAGE=${MASKROOM_IMAGE:-maskroom:local}
MASKROOM_DOMAIN=$DOMAIN
MASKROOM_PORT=8080

# sign-on: Maskroom's bundled Keycloak, served at https://$DOMAIN/sso
MASKROOM_AUTH_MODE=oidc
MASKROOM_OIDC_ISSUER=http://keycloak:8180/sso/realms/maskroom
MASKROOM_OIDC_CLIENT_ID=maskroom
MASKROOM_OIDC_CLIENT_SECRET=$(rand 24)
MASKROOM_SECRET_KEY=$(rand 32)
MASKROOM_SESSION_HOURS=12
MASKROOM_ADMIN_EMAILS=$ADMINS

# tokens and data
PII_TOKEN_SALT=$(rand 32)
SESSION_TTL_HOURS=24
AUDIT_TTL_DAYS=90
POSTGRES_PASSWORD=$(rand 16)

# Keycloak admin console (https://$DOMAIN/sso/admin/)
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$(rand 12)

# example users imported into the realm (change or delete them in Keycloak)
KC_STAFF_PASSWORD=$(rand 8)
KC_ADMIN_USER_PASSWORD=$(rand 8)
ENV
  chmod 600 .env
fi
if [ -n "${MASKROOM_IMAGE:-}" ]; then   # a newly shipped image: record its tag
  sed -i "s#^MASKROOM_IMAGE=.*#MASKROOM_IMAGE=${MASKROOM_IMAGE}#" .env
fi
set -a; . ./.env; set +a
: "${MASKROOM_DOMAIN:?MASKROOM_DOMAIN missing in .env}"
docker image inspect "$MASKROOM_IMAGE" >/dev/null 2>&1 || { echo "image $MASKROOM_IMAGE is not loaded on this server; run deploy/aws/ship.sh from a workstation"; exit 1; }

# ------------------------------------------------- realm import (rendered)
say "Rendering the Keycloak realm for $MASKROOM_DOMAIN"
mkdir -p data/keycloak-import
sed -e "s#REPLACE_HOST#${MASKROOM_DOMAIN}#g" \
    -e "s#change-me-maskroom-dev-secret#${MASKROOM_OIDC_CLIENT_SECRET}#" \
    -e "0,/\"value\": \"staff\"/s##\"value\": \"${KC_STAFF_PASSWORD:-staff}\"#" \
    -e "0,/\"value\": \"admin\"/s##\"value\": \"${KC_ADMIN_USER_PASSWORD:-admin}\"#" \
    keycloak/realm-maskroom.json > data/keycloak-import/realm-maskroom.json
chmod 600 data/keycloak-import/realm-maskroom.json

# ------------------------------------------------------- nginx + certificate
say "Rendering nginx config"
sed "s#__MASKROOM_DOMAIN__#${MASKROOM_DOMAIN}#g" nginx/maskroom.conf.template > nginx/maskroom.conf

# Certificate: a CA-issued pair named after the domain wins (<domain>.cer|.crt + <domain>.key),
# then the legacy maskroom.crt/.key; a self-signed pair is generated only when nothing exists.
mkdir -p "$CERT_DIR"
CRT=""; KEY=""
for c in "$CERT_DIR/$MASKROOM_DOMAIN.cer" "$CERT_DIR/$MASKROOM_DOMAIN.crt" "$CERT_DIR/$MASKROOM_DOMAIN.pem" "$CERT_DIR/maskroom.crt"; do
  [ -f "$c" ] && { CRT=$c; break; }
done
if [ -n "$CRT" ]; then
  KEY="${CRT%.*}.key"
  [ -f "$KEY" ] || { echo "found $CRT but no matching key $KEY"; exit 1; }
  if ! openssl x509 -in "$CRT" -noout 2>/dev/null; then       # DER-encoded .cer: convert to PEM
    say "Converting $CRT from DER to PEM"
    openssl x509 -inform der -in "$CRT" -out "$CERT_DIR/$MASKROOM_DOMAIN.crt" && CRT="$CERT_DIR/$MASKROOM_DOMAIN.crt"
  fi
  if [ "$(openssl x509 -in "$CRT" -noout -pubkey | openssl md5)" != "$(openssl pkey -in "$KEY" -pubout 2>/dev/null | openssl md5)" ]; then
    echo "certificate $CRT and key $KEY do not match"; exit 1
  fi
  n=$(grep -c "BEGIN CERTIFICATE" "$CRT")
  say "Using certificate $CRT ($(openssl x509 -in "$CRT" -noout -subject -enddate | tr '\n' ' '))"
  [ "$n" -gt 1 ] || echo "note: the file holds one certificate; if browsers report an incomplete chain, append the CA's intermediate certificate(s) to it"
else
  CRT="$CERT_DIR/$MASKROOM_DOMAIN.crt"; KEY="$CERT_DIR/$MASKROOM_DOMAIN.key"
  say "No certificate found: creating a self-signed one for $MASKROOM_DOMAIN in $CERT_DIR (replace with the real one later)"
  openssl req -x509 -newkey rsa:2048 -nodes -days 825 -keyout "$KEY" -out "$CRT" \
    -subj "/CN=${MASKROOM_DOMAIN}" -addext "subjectAltName=DNS:${MASKROOM_DOMAIN}" 2>/dev/null
fi
chmod 600 "$KEY" 2>/dev/null || true

say "Validating the nginx config"
docker run --rm \
  -v "$DEPLOY/nginx/maskroom.conf:/etc/nginx/conf.d/maskroom.conf:ro" \
  -v "$CRT:/etc/nginx/certs/maskroom.crt:ro" \
  -v "$KEY:/etc/nginx/certs/maskroom.key:ro" \
  nginx:1.31-alpine nginx -t 2>&1 | grep -E "syntax|test|emerg|error" || true

mkdir -p data
if [ "${MASKROOM_INSTALL_DRY_RUN:-0}" = "1" ]; then say "Dry run: files rendered, nothing started"; exit 0; fi

# ---------------------------------------------------------- optional swap
if [ ! -f /swapfile ] && sudo -n true 2>/dev/null; then
  say "Adding a 2 GB swapfile (safety net for the NLP model and OCR)"
  sudo fallocate -l 2G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile >/dev/null && sudo swapon /swapfile \
    && echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null || echo "swapfile skipped"
fi

# --------------------------------------------------------------------- run
say "Starting Maskroom from $MASKROOM_IMAGE"
$COMPOSE up -d
say "Waiting for the app to become healthy (model load on first start)"
st=starting
for i in $(seq 1 60); do
  st=$(docker inspect -f '{{.State.Health.Status}}' "$(${COMPOSE} ps -q app)" 2>/dev/null || echo starting)
  [ "$st" = healthy ] && break; sleep 5
done
[ "$st" = healthy ] || { echo "app is not healthy yet; check: $COMPOSE logs app"; exit 1; }

say "Warming the NLP model (one masking request through a temporary service key)"
KEY=$($COMPOSE exec -T app maskroom-admin key create warmup --role staff | sed -n 's/^secret (shown once): //p')
KID=$($COMPOSE exec -T app maskroom-admin key list | awk '/ warmup /{print $1}' | head -1)
$COMPOSE exec -T -e KEY="$KEY" app python - <<'PY' || echo "warm-up request failed (the model will load on the first real request)"
import json, os, urllib.request
req = urllib.request.Request("http://127.0.0.1:8080/api/mask", data=json.dumps({"text": "Warm up: Nimal Perera 0771234567"}).encode(),
                             headers={"Content-Type": "application/json", "Authorization": "Bearer " + os.environ["KEY"]})
print("warm-up:", urllib.request.urlopen(req, timeout=300).status)
PY
[ -n "$KID" ] && $COMPOSE exec -T app maskroom-admin key revoke "$KID" >/dev/null || true
docker image prune -f >/dev/null

# ------------------------------------------------------------------ done
cat <<MSG

==> Maskroom is running (project "maskroom", network "maskroom_default", image $MASKROOM_IMAGE).

Next, ONCE, in $PLATFORM_DIR/docker-compose.yaml give the platform's nginx access to it:

  services:
    nginx:
      networks: [default, maskroom]          # add
      volumes:                               # add these three lines to the existing list
        - $DEPLOY/nginx/maskroom.conf:/etc/nginx/conf.d/maskroom.conf:ro
        - $CRT:/etc/nginx/certs/maskroom.crt:ro
        - $KEY:/etc/nginx/certs/maskroom.key:ro
  networks:                                  # top level; add
    maskroom:
      external: true
      name: maskroom_default

then:  cd $PLATFORM_DIR && docker compose up -d nginx

Point the DNS A record for $MASKROOM_DOMAIN at this server, then verify:
  curl -k https://$MASKROOM_DOMAIN/api/config
  curl -k https://$MASKROOM_DOMAIN/sso/realms/maskroom/.well-known/openid-configuration | head -c 300

Sign-in users (change in Keycloak: https://$MASKROOM_DOMAIN/sso/admin/, admin / see .env):
  admin@example.com / $KC_ADMIN_USER_PASSWORD   (Maskroom admin if listed in MASKROOM_ADMIN_EMAILS)
  staff@example.com / $KC_STAFF_PASSWORD
MSG
